spring:
application:
name: db_alumnos

---

# Instancia 1
spring:
config:
activate:
on-profile: instancia1

datasource:
url: jdbc:oracle:thin:@localhost:1521:xe
username: SYSTEM
password: Lito2005
driver-class-name: oracle.jdbc.OracleDriver

jpa:
show-sql: true
properties:
hibernate:
dialect: org.hibernate.dialect.OracleDialect

server:
port: 8080

logging:
level:
org.springframework.security: DEBUG

---

# Instancia 2
spring:
config:
activate:
on-profile: instancia2

datasource:
url: jdbc:oracle:thin:@localhost:1521:xe
username: SYSTEM
password: Lito2005
driver-class-name: oracle.jdbc.OracleDriver

jpa:
show-sql: true
properties:
hibernate:
dialect: org.hibernate.dialect.OracleDialect

server:
port: 8081

logging:
level:
org.springframework.security: DEBUG

micrud-service:
  instances:
    - url: http://localhost:8080
    - url: http://localhost:8081