spring:
  application:
    name: db_alumnos
  profiles:
    default: instancia1

---

# Instancia 1 (puerto 8080)
spring:
  config:
    activate:
      on-profile: instancia1
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: Lito2005
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  application:
    name: db_alumnos

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

---

# Instancia 2 (puerto 8081)
spring:
  config:
    activate:
      on-profile: instancia2
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SYSTEM
    password: Lito2005
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  application:
    name: db_alumnos

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

---

# Cliente balanceador (puerto 8082) — sin base de datos
spring:
  config:
    activate:
      on-profile: cliente
  application:
    name: micrud-client
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8082

micrud-service:
  instances:
    - url: http://localhost:8080
    - url: http://localhost:8081